### ISSUE TITLE
Laat dit stukje inspringen zodat het er netjes uitziet

### ISSUE THREAD

**Issue by Knetters** [jtoufik/server-side-rendering#1]
Voor de netheid kan je dit laten inspringen. Dan staan er ook geen twee haakjes onder elkaar.

https://github.com/jtoufik/oba-server-side-rendering/blob/0cbdb9346c32dc88b82374ae1ff84ac13705efa1/index.js#L17

**Comment by JalalToufik** [comment]
Dit heb ik aangepast dankje wel voor je feedback
